// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type IndexDocumentDataSlicesSlice =
  | PinkProductCardSlice
  | SecondSliderSlice
  | BannerSlice
  | EditorsPickSlice
  | SliderSlice;

/**
 * Content for Index documents
 */
interface IndexDocumentData {
  /**
   * Slice Zone field in *Index*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: index.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<IndexDocumentDataSlicesSlice> /**
   * Meta Description field in *Index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: index.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Index*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: index.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Index*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: index.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Index document from Prismic
 *
 * - **API ID**: `index`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type IndexDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<IndexDocumentData>, "index", Lang>;

type ProductcardDocumentDataSlicesSlice =
  | PinkProductCardSlice
  | LogosSlice
  | ShopcardsSlice;

/**
 * Content for productCard documents
 */
interface ProductcardDocumentData {
  /**
   * Slice Zone field in *productCard*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: productcard.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductcardDocumentDataSlicesSlice> /**
   * Meta Description field in *productCard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: productcard.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *productCard*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: productcard.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *productCard*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: productcard.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * productCard document from Prismic
 *
 * - **API ID**: `productcard`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductcardDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProductcardDocumentData>,
    "productcard",
    Lang
  >;

type ProductpageDocumentDataSlicesSlice =
  | LogosSlice
  | PinkProductCardSlice
  | ProductDescriptionSlice
  | ProductCardSlice;

/**
 * Content for ProductPage documents
 */
interface ProductpageDocumentData {
  /**
   * Slice Zone field in *ProductPage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: productpage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ProductpageDocumentDataSlicesSlice> /**
   * Meta Description field in *ProductPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: productpage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *ProductPage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: productpage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *ProductPage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: productpage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * ProductPage document from Prismic
 *
 * - **API ID**: `productpage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProductpageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ProductpageDocumentData>,
    "productpage",
    Lang
  >;

export type AllDocumentTypes =
  | IndexDocument
  | ProductcardDocument
  | ProductpageDocument;

/**
 * Primary content in *Banner → Default → Primary*
 */
export interface BannerSliceDefaultPrimary {
  /**
   * Image field in *Banner → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Subtitle field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Title field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Banner → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *Banner → Items*
 */
export interface BannerSliceDefaultItem {
  /**
   * Button Caption field in *Banner → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.items[].button_caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_caption: prismic.KeyTextField;

  /**
   * className field in *Banner → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: banner.items[].classname
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  classname: prismic.KeyTextField;
}

/**
 * Default variation for Banner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BannerSliceDefaultPrimary>,
  Simplify<BannerSliceDefaultItem>
>;

/**
 * Slice variation for *Banner*
 */
type BannerSliceVariation = BannerSliceDefault;

/**
 * Banner Shared Slice
 *
 * - **API ID**: `banner`
 * - **Description**: Banner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BannerSlice = prismic.SharedSlice<"banner", BannerSliceVariation>;

/**
 * Primary content in *EditorsPick → Default → Primary*
 */
export interface EditorsPickSliceDefaultPrimary {
  /**
   * Title field in *EditorsPick → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: editors_pick.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *EditorsPick → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: editors_pick.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;
}

/**
 * Primary content in *EditorsPick → Items*
 */
export interface EditorsPickSliceDefaultItem {
  /**
   * Image field in *EditorsPick → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: editors_pick.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Button Caption field in *EditorsPick → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: editors_pick.items[].button_caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_caption: prismic.KeyTextField;
}

/**
 * Default variation for EditorsPick Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EditorsPickSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EditorsPickSliceDefaultPrimary>,
  Simplify<EditorsPickSliceDefaultItem>
>;

/**
 * Slice variation for *EditorsPick*
 */
type EditorsPickSliceVariation = EditorsPickSliceDefault;

/**
 * EditorsPick Shared Slice
 *
 * - **API ID**: `editors_pick`
 * - **Description**: EditorsPick
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EditorsPickSlice = prismic.SharedSlice<
  "editors_pick",
  EditorsPickSliceVariation
>;

/**
 * Primary content in *Logos → Items*
 */
export interface LogosSliceDefaultItem {
  /**
   * link field in *Logos → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * logo field in *Logos → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: logos.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for Logos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<LogosSliceDefaultItem>
>;

/**
 * Slice variation for *Logos*
 */
type LogosSliceVariation = LogosSliceDefault;

/**
 * Logos Shared Slice
 *
 * - **API ID**: `logos`
 * - **Description**: Logos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosSlice = prismic.SharedSlice<"logos", LogosSliceVariation>;

/**
 * Primary content in *PinkProductCard → Default → Primary*
 */
export interface PinkProductCardSliceDefaultPrimary {
  /**
   * heart field in *PinkProductCard → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pink_product_card.default.primary.heart
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  heart: prismic.ImageField<never>;

  /**
   * cart field in *PinkProductCard → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pink_product_card.default.primary.cart
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cart: prismic.ImageField<never>;

  /**
   * eye field in *PinkProductCard → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pink_product_card.default.primary.eye
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  eye: prismic.ImageField<never>;
}

/**
 * Primary content in *PinkProductCard → Items*
 */
export interface PinkProductCardSliceDefaultItem {
  /**
   * Image field in *PinkProductCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pink_product_card.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *PinkProductCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pink_product_card.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Category field in *PinkProductCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pink_product_card.items[].category
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  category: prismic.KeyTextField;

  /**
   * OldPrice field in *PinkProductCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pink_product_card.items[].oldPrice
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  oldPrice: prismic.KeyTextField;

  /**
   * NewPrice field in *PinkProductCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pink_product_card.items[].newPrice
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  newPrice: prismic.KeyTextField;

  /**
   * Descr field in *PinkProductCard → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pink_product_card.items[].descr
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descr: prismic.RichTextField;

  /**
   * miniImage field in *PinkProductCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pink_product_card.items[].miniImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  miniImage: prismic.ImageField<never>;

  /**
   * miniImage1 field in *PinkProductCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pink_product_card.items[].miniImage1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  miniImage1: prismic.ImageField<never>;
}

/**
 * Default variation for PinkProductCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PinkProductCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PinkProductCardSliceDefaultPrimary>,
  Simplify<PinkProductCardSliceDefaultItem>
>;

/**
 * Slice variation for *PinkProductCard*
 */
type PinkProductCardSliceVariation = PinkProductCardSliceDefault;

/**
 * PinkProductCard Shared Slice
 *
 * - **API ID**: `pink_product_card`
 * - **Description**: PinkProductCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PinkProductCardSlice = prismic.SharedSlice<
  "pink_product_card",
  PinkProductCardSliceVariation
>;

/**
 * Primary content in *ProductCard → Items*
 */
export interface ProductCardSliceDefaultItem {
  /**
   * mainImage field in *ProductCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.items[].mainImage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  mainImage: prismic.ImageField<never>;

  /**
   * Title field in *ProductCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * fullStar field in *ProductCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.items[].fullStar
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  fullStar: prismic.ImageField<never>;

  /**
   * emptyStar field in *ProductCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.items[].emptyStar
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  emptyStar: prismic.ImageField<never>;

  /**
   * reviews field in *ProductCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.items[].reviews
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  reviews: prismic.KeyTextField;

  /**
   * price field in *ProductCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.items[].price
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price: prismic.KeyTextField;

  /**
   * Availability field in *ProductCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.items[].availability
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  availability: prismic.KeyTextField;

  /**
   * Descr field in *ProductCard → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.items[].descr
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descr: prismic.RichTextField;

  /**
   * Circle field in *ProductCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.items[].circle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  circle: prismic.KeyTextField;

  /**
   * ButtonSelect field in *ProductCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.items[].buttonSelect
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  buttonSelect: prismic.KeyTextField;

  /**
   * heart field in *ProductCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.items[].heart
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  heart: prismic.ImageField<never>;

  /**
   * cart field in *ProductCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.items[].cart
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cart: prismic.ImageField<never>;

  /**
   * eye field in *ProductCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.items[].eye
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  eye: prismic.ImageField<never>;

  /**
   * miniImg field in *ProductCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.items[].miniImg
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  miniImg: prismic.ImageField<never>;

  /**
   * miniImg1 field in *ProductCard → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_card.items[].miniImg1
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  miniImg1: prismic.ImageField<never>;
}

/**
 * Default variation for ProductCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ProductCardSliceDefaultItem>
>;

/**
 * Slice variation for *ProductCard*
 */
type ProductCardSliceVariation = ProductCardSliceDefault;

/**
 * ProductCard Shared Slice
 *
 * - **API ID**: `product_card`
 * - **Description**: ProductCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductCardSlice = prismic.SharedSlice<
  "product_card",
  ProductCardSliceVariation
>;

/**
 * Primary content in *ProductDescription → Default → Primary*
 */
export interface ProductDescriptionSliceDefaultPrimary {
  /**
   * Button field in *ProductDescription → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_description.default.primary.button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button: prismic.KeyTextField;

  /**
   * Button field in *ProductDescription → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_description.default.primary.button2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button2: prismic.KeyTextField;

  /**
   * Button3 field in *ProductDescription → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_description.default.primary.button3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button3: prismic.KeyTextField;

  /**
   * image field in *ProductDescription → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_description.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *ProductDescription → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_description.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Descr field in *ProductDescription → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_description.default.primary.descr
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descr: prismic.RichTextField;

  /**
   * Title2 field in *ProductDescription → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_description.default.primary.title2
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title2: prismic.KeyTextField;

  /**
   * Title3 field in *ProductDescription → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_description.default.primary.title3
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title3: prismic.KeyTextField;

  /**
   * Arrow field in *ProductDescription → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_description.default.primary.arrow
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  arrow: prismic.ImageField<never>;
}

/**
 * Primary content in *ProductDescription → Items*
 */
export interface ProductDescriptionSliceDefaultItem {
  /**
   * ListItem field in *ProductDescription → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: product_description.items[].listItem
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  listItem: prismic.KeyTextField;
}

/**
 * Default variation for ProductDescription Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductDescriptionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductDescriptionSliceDefaultPrimary>,
  Simplify<ProductDescriptionSliceDefaultItem>
>;

/**
 * Slice variation for *ProductDescription*
 */
type ProductDescriptionSliceVariation = ProductDescriptionSliceDefault;

/**
 * ProductDescription Shared Slice
 *
 * - **API ID**: `product_description`
 * - **Description**: ProductDescription
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProductDescriptionSlice = prismic.SharedSlice<
  "product_description",
  ProductDescriptionSliceVariation
>;

/**
 * Primary content in *SecondSlider → Items*
 */
export interface SecondSliderSliceDefaultItem {
  /**
   * subtitle field in *SecondSlider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_slider.items[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * title field in *SecondSlider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_slider.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * descr field in *SecondSlider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_slider.items[].descr
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  descr: prismic.KeyTextField;

  /**
   * price field in *SecondSlider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_slider.items[].price
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price: prismic.KeyTextField;

  /**
   * button field in *SecondSlider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_slider.items[].button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button: prismic.KeyTextField;

  /**
   * image field in *SecondSlider → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: second_slider.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * id field in *SecondSlider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_slider.items[].sliderID
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  sliderID: prismic.KeyTextField;

  /**
   * displayNo field in *SecondSlider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: second_slider.items[].displayno
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  displayno: prismic.KeyTextField;
}

/**
 * Default variation for SecondSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecondSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SecondSliderSliceDefaultItem>
>;

/**
 * Slice variation for *SecondSlider*
 */
type SecondSliderSliceVariation = SecondSliderSliceDefault;

/**
 * SecondSlider Shared Slice
 *
 * - **API ID**: `second_slider`
 * - **Description**: SecondSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SecondSliderSlice = prismic.SharedSlice<
  "second_slider",
  SecondSliderSliceVariation
>;

/**
 * Primary content in *Shopcards → Items*
 */
export interface ShopcardsSliceDefaultItem {
  /**
   * CardLink field in *Shopcards → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: shopcards.items[].cardlink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cardlink: prismic.LinkField;

  /**
   * CardImage field in *Shopcards → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: shopcards.items[].cardimage
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cardimage: prismic.ImageField<never>;

  /**
   * CardTitle field in *Shopcards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shopcards.items[].cardtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardtitle: prismic.KeyTextField;

  /**
   * CardSubtitle field in *Shopcards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: shopcards.items[].cardsubtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cardsubtitle: prismic.KeyTextField;
}

/**
 * Default variation for Shopcards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShopcardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ShopcardsSliceDefaultItem>
>;

/**
 * Slice variation for *Shopcards*
 */
type ShopcardsSliceVariation = ShopcardsSliceDefault;

/**
 * Shopcards Shared Slice
 *
 * - **API ID**: `shopcards`
 * - **Description**: Shopcards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ShopcardsSlice = prismic.SharedSlice<
  "shopcards",
  ShopcardsSliceVariation
>;

/**
 * Primary content in *Slider → Items*
 */
export interface SliderSliceDefaultItem {
  /**
   * Image field in *Slider → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Slider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Season field in *Slider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.items[].season
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  season: prismic.KeyTextField;

  /**
   * Description field in *Slider → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Button Caption field in *Slider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider.items[].button_caption
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_caption: prismic.KeyTextField;
}

/**
 * Default variation for Slider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SliderSliceDefaultItem>
>;

/**
 * Slice variation for *Slider*
 */
type SliderSliceVariation = SliderSliceDefault;

/**
 * Slider Shared Slice
 *
 * - **API ID**: `slider`
 * - **Description**: Slider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderSlice = prismic.SharedSlice<"slider", SliderSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      IndexDocument,
      IndexDocumentData,
      IndexDocumentDataSlicesSlice,
      ProductcardDocument,
      ProductcardDocumentData,
      ProductcardDocumentDataSlicesSlice,
      ProductpageDocument,
      ProductpageDocumentData,
      ProductpageDocumentDataSlicesSlice,
      AllDocumentTypes,
      BannerSlice,
      BannerSliceDefaultPrimary,
      BannerSliceDefaultItem,
      BannerSliceVariation,
      BannerSliceDefault,
      EditorsPickSlice,
      EditorsPickSliceDefaultPrimary,
      EditorsPickSliceDefaultItem,
      EditorsPickSliceVariation,
      EditorsPickSliceDefault,
      LogosSlice,
      LogosSliceDefaultItem,
      LogosSliceVariation,
      LogosSliceDefault,
      PinkProductCardSlice,
      PinkProductCardSliceDefaultPrimary,
      PinkProductCardSliceDefaultItem,
      PinkProductCardSliceVariation,
      PinkProductCardSliceDefault,
      ProductCardSlice,
      ProductCardSliceDefaultItem,
      ProductCardSliceVariation,
      ProductCardSliceDefault,
      ProductDescriptionSlice,
      ProductDescriptionSliceDefaultPrimary,
      ProductDescriptionSliceDefaultItem,
      ProductDescriptionSliceVariation,
      ProductDescriptionSliceDefault,
      SecondSliderSlice,
      SecondSliderSliceDefaultItem,
      SecondSliderSliceVariation,
      SecondSliderSliceDefault,
      ShopcardsSlice,
      ShopcardsSliceDefaultItem,
      ShopcardsSliceVariation,
      ShopcardsSliceDefault,
      SliderSlice,
      SliderSliceDefaultItem,
      SliderSliceVariation,
      SliderSliceDefault,
    };
  }
}
