// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  banner: dynamic(() => import("./Banner")),
  editors_pick: dynamic(() => import("./EditorsPick")),
  logos: dynamic(() => import("./Logos")),
  pink_product_card: dynamic(() => import("./PinkProductCard")),
  product_card: dynamic(() => import("./ProductCard")),
  product_description: dynamic(() => import("./ProductDescription")),
  second_slider: dynamic(() => import("./SecondSlider")),
  shopcards: dynamic(() => import("./Shopcards")),
  slider: dynamic(() => import("./Slider")),
};
