import { createClient } from "@/prismicio";
import Main from "./Main";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function Home() {
  const client = createClient();

  const { data } = await client.getSingle("index");

  return (
    <>
      <Main data={data} />
    </>
  );
}
